version: '3.8'
services:
  azimut:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - ORACLE_SID=MYDEMOSID
      - ORACLE_USER=MYDEMOUSER
      - ORACLE_PASSWORD=MYDEMOPASSWORD
      - ORACLE_CONNECTION=connection_string
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www
    ports:
      - "443:443"